const allJobs = [
  {
    id: "1",
    title: "Desenvolvedor Full Stack",
    description: "Desenvolva e mantenha aplicativos web inovadores.",
    salary: "$80,000 - $100,000/ano",
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Líder em armazenamento em nuvem.",
      reviews: "4.5/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "2",
    title: "Especialista em Marketing Online",
    description:
      "Execute campanhas de marketing digital e otimize a presença online.",
    salary: "$70,000 - $90,000/ano",
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/facebook.png",
      name: "Facebook",
      about: "Maior plataforma de mídia social do mundo.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "3",
    title: "Engenheiro de Segurança de Dados",
    description:
      "Proteja dados sensíveis e desenvolva estratégias de segurança.",
    salary: "$90,000 - $110,000/ano",
    location: "Mountain View, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/instagram.png",
      name: "Instagram",
      about: "Empresa de tecnologia líder em busca e serviços online.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "4",
    title: "Designer UI/UX",
    description: "Crie experiências de usuário intuitivas e atraentes.",
    salary: "$75,000 - $95,000/ano",
    location: "Palo Alto, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/behance.png",
      name: "Evernote",
      about: "Aplicativo de organização de notas e tarefas.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "5",
    title: "Analista de Dados Sênior",
    description:
      "Analise e interprete grandes conjuntos de dados para insights valiosos.",
    salary: "$85,000 - $105,000/ano",
    location: "Sunnyvale, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/linkedin.png",
      name: "LinkedIn",
      about: "Rede profissional e plataforma de busca de empregos.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "6",
    title: "Engenheiro de Software",
    description:
      "Desenvolva e mantenha sistemas escaláveis para uma experiência de usuário excepcional.",
    salary: "$85,000 - $110,000/ano",
    location: "Seattle, WA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Maior varejista online e provedor de serviços em nuvem.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "7",
    title: "Gerente de Produto",
    description:
      "Liderar o ciclo de vida do produto, desde a concepção até o lançamento.",
    salary: "$95,000 - $120,000/ano",
    location: "Cupertino, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/apple.png",
      name: "Apple",
      about:
        "Empresa de tecnologia inovadora e fabricante de dispositivos eletrônicos.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "8",
    title: "Analista de Suporte Técnico",
    description:
      "Ofereça suporte técnico eficaz para resolver problemas de hardware e software.",
    salary: "$60,000 - $75,000/ano",
    location: "Austin, TX",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/paypal.png",
      name: "PayPall",
      about: "Empresa de tecnologia que oferece soluções de computação.",
      reviews: "4.4/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "9",
    title: "Cientista de Dados",
    description:
      "Conduza análises avançadas para extrair insights valiosos de conjuntos de dados complexos.",
    salary: "$90,000 - $115,000/ano",
    location: "New York, NY",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/tiktok.png",
      name: "TikTok",
      about: "Empresa de tecnologia e consultoria global.",
      reviews: "4.5/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "10",
    title: "Especialista em Recursos Humanos",
    description:
      "Gerencie processos de recrutamento, seleção e desenvolvimento de talentos.",
    salary: "$70,000 - $90,000/ano",
    location: "Los Angeles, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/netflix.png",
      name: "Netflix",
      about: "Plataforma líder de streaming de entretenimento.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "11",
    title: "Desenvolvedor Mobile iOS",
    description: "Desenvolva aplicativos iOS inovadores para a Apple.",
    salary: "$90,000 - $110,000/ano",
    location: "Cupertino, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/apple.png",
      name: "Apple",
      about: "Líder em tecnologia e inovação.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "12",
    title: "Designer de UI/UX",
    description: "Crie experiências visuais incríveis para a Behance.",
    salary: "$75,000 - $95,000/ano",
    location: "Nova Iorque, NY",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/behance.png",
      name: "Behance",
      about: "Plataforma de exibição de portfólios criativos.",
      reviews: "4.5/5 estrelas",
    },
    type: "Meio Período",
    category: "popular",
  },
  {
    id: "13",
    title: "Engenheiro de Backend",
    description:
      "Desenvolva e mantenha a infraestrutura de servidores do Discord.",
    salary: "$85,000 - $105,000/ano",
    location: "São Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/discord.png",
      name: "Discord",
      about: "Plataforma de comunicação para gamers.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "14",
    title: "Engenheiro de Software",
    description:
      "Contribua para o desenvolvimento de soluções inovadoras de armazenamento em nuvem.",
    salary: "$80,000 - $100,000/ano",
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Líder em armazenamento em nuvem.",
      reviews: "4.5/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "15",
    title: "Engenheiro de Segurança",
    description:
      "Proteja a infraestrutura de uma das maiores redes sociais do mundo.",
    salary: "$95,000 - $115,000/ano",
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/facebook.png",
      name: "Facebook",
      about: "Rede social global.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "16",
    title: "Desenvolvedor Frontend",
    description:
      "Colabore no desenvolvimento de interfaces de usuário para plataformas de desenvolvimento.",
    salary: "$85,000 - $105,000/ano",
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/github.png",
      name: "Github",
      about: "Plataforma de hospedagem e colaboração de código.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "17",
    title: "Engenheiro de Software",
    description:
      "Trabalhe em projetos inovadores para uma das maiores empresas de tecnologia do mundo.",
    salary: "$90,000 - $110,000/ano",
    location: "Mountain View, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Gigante da tecnologia.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "18",
    title: "Designer de Produto",
    description: "Desenvolva designs envolventes para a plataforma Instagram.",
    salary: "$80,000 - $100,000/ano",
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/instagram.png",
      name: "Instagram",
      about: "Plataforma de compartilhamento de fotos e vídeos.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "19",
    title: "Analista de Dados",
    description:
      "Analise dados para insights valiosos na maior rede profissional do mundo.",
    salary: "$85,000 - $105,000/ano",
    location: "Sunnyvale, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/linkedin.png",
      name: "Linkedin",
      about: "Rede profissional online.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "20",
    title: "Engenheiro de Sistemas",
    description:
      "Trabalhe no desenvolvimento e manutenção de sistemas para uma empresa líder em streaming.",
    salary: "$95,000 - $115,000/ano",
    location: "Los Gatos, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/netflix.png",
      name: "Netflix",
      about: "Plataforma de streaming de vídeo.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "21",
    title: "Desenvolvedor Android",
    description: "Crie aplicativos Android inovadores para o Paypal.",
    salary: "$85,000 - $105,000/ano",
    location: "San Jose, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/paypal.png",
      name: "Paypal",
      about: "Plataforma de pagamentos online.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "22",
    title: "Engenheiro de Software",
    description: "Colabore no desenvolvimento de recursos para o Pinterest.",
    salary: "$90,000 - $110,000/ano",
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/pinterest.png",
      name: "Pinterest",
      about: "Plataforma de descoberta visual.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "23",
    title: "Desenvolvedor Backend",
    description: "Trabalhe na infraestrutura de servidores para o SoundCloud.",
    salary: "$80,000 - $100,000/ano",
    location: "Berlim, Alemanha",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/soundcloud.png",
      name: "SoundCloud",
      about: "Plataforma de distribuição de áudio.",
      reviews: "4.5/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "24",
    title: "Engenheiro de Software - Spotify",
    description:
      "Contribua para o desenvolvimento da plataforma de streaming de música Spotify.",
    salary: "$95,000 - $115,000/ano",
    location: "Estocolmo, Suécia",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/spotify.png",
      name: "Spotify",
      about: "Plataforma de streaming de música.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "25",
    title: "Desenvolvedor Full Stack",
    description:
      "Colabore no desenvolvimento de aplicativos inovadores para o Twitch.",
    salary: "$90,000 - $110,000/ano",
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/twitch.png",
      name: "Twitch",
      about: "Plataforma de streaming ao vivo.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "26",
    title: "Desenvolvedor Mobile",
    description: "Trabalhe no desenvolvimento de recursos para o Whatsapp.",
    salary: "$85,000 - $105,000/ano",
    location: "Mountain View, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/whatsapp.png",
      name: "Whatsapp",
      about: "Plataforma de mensagens instantâneas.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
  },
  {
    id: "27",
    title: "Engenheiro de Machine Learning",
    description:
      "Trabalhe em projetos avançados de aprendizado de máquina para a Apple.",
    salary: "$100,000 - $120,000/ano",
    location: "Cupertino, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/apple.png",
      name: "Apple",
      about: "Líder em tecnologia e inovação.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "28",
    title: "Designer de Interfaces",
    description: "Crie designs inovadores para a Behance.",
    salary: "$80,000 - $100,000/ano",
    location: "Nova Iorque, NY",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/behance.png",
      name: "Behance",
      about: "Plataforma de exibição de portfólios criativos.",
      reviews: "4.5/5 estrelas",
    },
    type: "Meio Período",
    category: "recent-posted",
  },
  {
    id: "29",
    title: "Engenheiro de Software - Discord",
    description: "Desenvolva recursos para a plataforma Discord.",
    salary: "$90,000 - $110,000/ano",
    location: "São Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/discord.png",
      name: "Discord",
      about: "Plataforma de comunicação para gamers.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "30",
    title: "Engenheiro de Segurança - Dropbox",
    description:
      "Mantenha a segurança dos serviços de armazenamento em nuvem da Dropbox.",
    salary: "$85,000 - $105,000/ano",
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Líder em armazenamento em nuvem.",
      reviews: "4.5/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "31",
    title: "Engenheiro de Software Sênior - Facebook",
    description:
      "Liderança técnica no desenvolvimento de novos recursos para a rede social.",
    salary: "$110,000 - $130,000/ano",
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/facebook.png",
      name: "Facebook",
      about: "Rede social global.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "32",
    title: "Desenvolvedor Frontend Sênior - Github",
    description:
      "Liderança no desenvolvimento de interfaces de usuário para plataformas de código aberto.",
    salary: "$100,000 - $120,000/ano",
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/github.png",
      name: "Github",
      about: "Plataforma de hospedagem e colaboração de código.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "33",
    title: "Engenheiro de Software - Google",
    description:
      "Colabore em projetos inovadores para uma das maiores empresas de tecnologia do mundo.",
    salary: "$95,000 - $115,000/ano",
    location: "Mountain View, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Gigante da tecnologia.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "34",
    title: "Designer de Produto - Instagram",
    description: "Desenvolva designs envolventes para a plataforma Instagram.",
    salary: "$85,000 - $105,000/ano",
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/instagram.png",
      name: "Instagram",
      about: "Plataforma de compartilhamento de fotos e vídeos.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "35",
    title: "Cientista de Dados - Linkedin",
    description:
      "Analise dados para insights valiosos na maior rede profissional do mundo.",
    salary: "$90,000 - $110,000/ano",
    location: "Sunnyvale, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/linkedin.png",
      name: "Linkedin",
      about: "Rede profissional online.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "36",
    title: "Engenheiro de Software - Netflix",
    description:
      "Trabalhe no desenvolvimento e manutenção de sistemas para uma empresa líder em streaming.",
    salary: "$100,000 - $120,000/ano",
    location: "Los Gatos, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/netflix.png",
      name: "Netflix",
      about: "Plataforma de streaming de vídeo.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "37",
    title: "Desenvolvedor Android - Paypal",
    description:
      "Crie aplicativos Android inovadores para a plataforma de pagamentos online Paypal.",
    salary: "$95,000 - $115,000/ano",
    location: "San Jose, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/paypal.png",
      name: "Paypal",
      about: "Plataforma de pagamentos online.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "38",
    title: "Desenvolvedor Frontend - Pinterest",
    description:
      "Trabalhe no desenvolvimento de recursos para a plataforma de descoberta visual Pinterest.",
    salary: "$90,000 - $110,000/ano",
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/pinterest.png",
      name: "Pinterest",
      about: "Plataforma de descoberta visual.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "39",
    title: "Engenheiro de Backend - SoundCloud",
    description:
      "Trabalhe na infraestrutura de servidores para a plataforma de distribuição de áudio SoundCloud.",
    salary: "$80,000 - $100,000/ano",
    location: "Berlim, Alemanha",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/soundcloud.png",
      name: "SoundCloud",
      about: "Plataforma de distribuição de áudio.",
      reviews: "4.5/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "40",
    title: "Desenvolvedor Mobile - Spotify",
    description:
      "Contribua para o desenvolvimento da plataforma de streaming de música Spotify.",
    salary: "$100,000 - $120,000/ano",
    location: "Estocolmo, Suécia",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/spotify.png",
      name: "Spotify",
      about: "Plataforma de streaming de música.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "41",
    title: "Desenvolvedor Full Stack - Twitch",
    description:
      "Colabore no desenvolvimento de aplicativos inovadores para a plataforma de streaming ao vivo Twitch.",
    salary: "$95,000 - $115,000/ano",
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/twitch.png",
      name: "Twitch",
      about: "Plataforma de streaming ao vivo.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
  {
    id: "42",
    title: "Desenvolvedor Mobile - Whatsapp",
    description:
      "Trabalhe no desenvolvimento de recursos para a plataforma de mensagens instantâneas Whatsapp.",
    salary: "$90,000 - $110,000/ano",
    location: "Mountain View, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/whatsapp.png",
      name: "Whatsapp",
      about: "Plataforma de mensagens instantâneas.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
  },
];

export default allJobs;
