const allJobs = [
  {
    id: "1",
    title: "iOS Developer - Apple",
    description: "Develop innovative applications for Apple's iOS platform.",
    salary: {
      entry: "90,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Cupertino, CA",
    company: {
      logoUrl: "URL_DA_LOGO",
      name: "Apple",
      about: "Inovação em tecnologia e design.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "2",
    title: "Social Media Manager - Instagram",
    description: "Manage and execute social media strategies for Instagram.",
    salary: {
      entry: "75,000",
      end: "95,000",
      symbol: "$",
      time: "ano",
    },
    location: "Menlo Park, CA",
    company: {
      logoUrl: "URL_DA_LOGO",
      name: "Instagram",
      about: "Compartilhamento visual e redes sociais.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "3",
    title: "UX/UI Designer - Behance",
    description:
      "Crie experiências de usuário excepcionais para a plataforma Behance.",
    salary: {
      entry: "80,000",
      end: "100,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "URL_DA_LOGO",
      name: "Behance",
      about: "Plataforma de portfólios criativos.",
      reviews: "4.5/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "4",
    title: "Community Manager - Discord",
    description: "Gerencie e promova a comunidade Discord.",
    salary: {
      entry: "70,000",
      end: "90,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "URL_DA_LOGO",
      name: "Discord",
      about: "Plataforma de comunicação para gamers.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "finished",
  },
  {
    id: "5",
    title: "Product Manager - Dropbox",
    description:
      "Gerencie o ciclo de vida de produtos para a plataforma Dropbox.",
    salary: {
      entry: "95,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "URL_DA_LOGO",
      name: "Dropbox",
      about: "Soluções de armazenamento em nuvem.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "finished",
  },
  {
    id: "6",
    title: "AI Researcher - Google",
    description:
      "Conduza pesquisas inovadoras em inteligência artificial para o Google.",
    salary: {
      entry: "100,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Mountain View, CA",
    company: {
      logoUrl: "URL_DA_LOGO",
      name: "Google",
      about: "Empresa líder em tecnologia de busca e inovação.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "finished",
  },
  {
    id: "7",
    title: "Software Engineer - Github",
    description: "Desenvolva e aprimore a plataforma Github.",
    salary: {
      entry: "85,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "URL_DA_LOGO",
      name: "Github",
      about: "Plataforma de desenvolvimento colaborativo.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "8",
    title: "AR/VR Developer - Facebook",
    description:
      "Trabalhe na vanguarda da tecnologia de realidade aumentada/virtual para o Facebook.",
    salary: {
      entry: "90,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "Menlo Park, CA",
    company: {
      logoUrl: "URL_DA_LOGO",
      name: "Facebook",
      about: "Rede social líder global.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "9",
    title: "Machine Learning Engineer - Netflix",
    description:
      "Aplique algoritmos de aprendizado de máquina para melhorar a experiência do usuário na Netflix.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Los Gatos, CA",
    company: {
      logoUrl: "URL_DA_LOGO",
      name: "Netflix",
      about: "Plataforma de streaming líder.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
];

export default allJobs;
