const allJobs = [
  {
    id: "1",
    title: "iOS Developer",
    description: "Develop innovative applications for Apple's iOS platform.",
    salary: {
      entry: "90,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Cupertino, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/apple.png",
      name: "Apple",
      about: "Inovação em tecnologia e design.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "2",
    title: "Social Media Manager",
    description: "Manage and execute social media strategies for Instagram.",
    salary: {
      entry: "75,000",
      end: "95,000",
      symbol: "$",
      time: "ano",
    },
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/instagram.png",
      name: "Instagram",
      about: "Compartilhamento visual e redes sociais.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "3",
    title: "UX/UI Designer",
    description:
      "Crie experiências de usuário excepcionais para a plataforma Behance.",
    salary: {
      entry: "80,000",
      end: "100,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/behance.png",
      name: "Behance",
      about: "Plataforma de portfólios criativos.",
      reviews: "4.5/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "4",
    title: "Community Manager",
    description: "Gerencie e promova a comunidade Discord.",
    salary: {
      entry: "70,000",
      end: "90,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/discord.png",
      name: "Discord",
      about: "Plataforma de comunicação para gamers.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "finished",
  },
  {
    id: "5",
    title: "Product Manager",
    description:
      "Gerencie o ciclo de vida de produtos para a plataforma Dropbox.",
    salary: {
      entry: "95,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Soluções de armazenamento em nuvem.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "finished",
  },
  {
    id: "6",
    title: "AI Researcher",
    description:
      "Conduza pesquisas inovadoras em inteligência artificial para o Google.",
    salary: {
      entry: "100,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Mountain View, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Empresa líder em tecnologia de busca e inovação.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "finished",
  },
  {
    id: "7",
    title: "Software Engineer",
    description: "Desenvolva e aprimore a plataforma Github.",
    salary: {
      entry: "85,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/github.png",
      name: "Github",
      about: "Plataforma de desenvolvimento colaborativo.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "8",
    title: "AR/VR Developer",
    description:
      "Trabalhe na vanguarda da tecnologia de realidade aumentada/virtual para o Facebook.",
    salary: {
      entry: "90,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/facebook.png",
      name: "Facebook",
      about: "Rede social líder global.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "9",
    title: "Machine Learning Engineer",
    description:
      "Aplique algoritmos de aprendizado de máquina para melhorar a experiência do usuário na Netflix.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Los Gatos, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/netflix.png",
      name: "Netflix",
      about: "Plataforma de streaming líder.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "11",
    title: "Frontend Developer",
    description:
      "Crie interfaces de usuário incríveis para a plataforma de colaboração do Dropbox.",
    salary: {
      entry: "80,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Soluções de armazenamento em nuvem.",
      reviews: "4.5/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "12",
    title: "Software Engineer (Internship)",
    description:
      "Colabore no desenvolvimento de novos recursos para a plataforma de comunicação do Discord.",
    salary: {
      entry: "35,000",
      end: "45,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/discord.png",
      name: "Discord",
      about: "Plataforma de comunicação para comunidades.",
      reviews: "4.6/5 estrelas",
    },
    type: "Internship",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "13",
    title: "UX Designer",
    description:
      "Crie experiências de usuário intuitivas para a próxima geração de dispositivos Apple.",
    salary: {
      entry: "110,000",
      end: "140,000",
      symbol: "$",
      time: "ano",
    },
    location: "Cupertino, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/apple.png",
      name: "Apple",
      about: "Inovação em eletrônicos de consumo.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "14",
    title: "Social Media Manager",
    description:
      "Estruture estratégias de marketing digital para impulsionar a presença do Google nas redes sociais.",
    salary: {
      entry: "90,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "Mountain View, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Empresa de tecnologia líder em pesquisa na web.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "16",
    title: "AI Research Scientist",
    description:
      "Conduza pesquisas inovadoras em inteligência artificial para a Facebook AI Research em Menlo Park, CA.",
    salary: {
      entry: "120,000",
      end: "150,000",
      symbol: "$",
      time: "ano",
    },
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/facebook.png",
      name: "Facebook",
      about: "Plataforma de mídia social global.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "17",
    title: "Graphic Designer (Part Time)",
    description:
      "Crie designs visuais impactantes para a plataforma de música Spotify em seu tempo flexível.",
    salary: {
      entry: "50,000",
      end: "65,000",
      symbol: "$",
      time: "ano",
    },
    location: "New York, NY",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/spotify.png",
      name: "Spotify",
      about: "Plataforma de streaming de música.",
      reviews: "4.5/5 estrelas",
    },
    type: "Part Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "25",
    title: "Data Scientist",
    description:
      "Analyze and interpret complex data sets to inform business decision-making at Google.",
    salary: {
      entry: "100,000",
      end: "130,000",
      symbol: "$",
      time: "ano",
    },
    location: "Mountain View, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Global technology leader.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "26",
    title: "UX/UI Designer",
    description:
      "Create visually appealing and user-friendly interfaces for Facebook's social media platforms.",
    salary: {
      entry: "90,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/facebook.png",
      name: "Facebook",
      about: "Connecting people worldwide.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "27",
    title: "Software Engineer Intern",
    description:
      "Gain hands-on experience in software development with a summer internship at Dropbox.",
    salary: {
      entry: "25",
      end: "30",
      symbol: "$",
      time: "hora",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Simplify your work, collaborate effortlessly.",
      reviews: "4.6/5 estrelas",
    },
    type: "InternShip",
    category: "recent-posted",
    status: "delivered",
  },
  {
    id: "29",
    title: "Software Developer",
    description:
      "Contribute to exciting projects at Github while maintaining a flexible part-time schedule.",
    salary: {
      entry: "40",
      end: "50",
      symbol: "$",
      time: "hora",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/github.png",
      name: "GitHub",
      about: "Build software better, together.",
      reviews: "4.7/5 estrelas",
    },
    type: "Part Time",
    category: "recent-posted",
    status: "analyzing",
  },
  {
    id: "31",
    title: "Frontend Developer",
    description:
      "Crie interfaces de usuário atraentes para a Google Workspace.",
    salary: {
      entry: "85,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "Mountain View, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Empresa de tecnologia global.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "33",
    title: "UX/UI Designer",
    description:
      "Transforme a experiência do usuário na Apple através de design inovador.",
    salary: {
      entry: "110,000",
      end: "140,000",
      symbol: "$",
      time: "ano",
    },
    location: "Cupertino, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/apple.png",
      name: "Apple",
      about: "Empresa de tecnologia icônica.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "34",
    title: "Cybersecurity Analyst",
    description:
      "Proteja os dados confidenciais na Facebook através de análise de ameaças.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Menlo Park, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/facebook.png",
      name: "Facebook",
      about: "Rede social líder mundial.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "GEREUMTX",
    title: "Machine Learning Engineer",
    description:
      "Aplique algoritmos de aprendizado de máquina para melhorar a experiência do usuário na Netflix.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Los Gatos, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/netflix.png",
      name: "Netflix",
      about: "Plataforma de streaming líder.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB1",
    title: "Web Developer",
    description:
      "Desenvolva interfaces web modernas e responsivas para aprimorar a experiência do usuário.",
    salary: {
      entry: "70,000",
      end: "90,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/github.png",
      name: "GitHub",
      about: "Plataforma de desenvolvimento colaborativo.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB2",
    title: "Data Scientist",
    description:
      "Analise grandes conjuntos de dados para extrair insights valiosos e informar decisões estratégicas.",
    salary: {
      entry: "80,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "New York, NY",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/spotify.png",
      name: "Spotify",
      about: "Plataforma de streaming de música.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "analyzing",
  },
  {
    id: "JOB3",
    title: "UX/UI Designer",
    description:
      "Crie interfaces intuitivas e atraentes para proporcionar uma experiência de usuário excepcional.",
    salary: {
      entry: "75,000",
      end: "100,000",
      symbol: "$",
      time: "ano",
    },
    location: "Los Angeles, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/behance.png",
      name: "Behance",
      about: "Plataforma de portfólios criativos.",
      reviews: "4.6/5 estrelas",
    },
    type: "Internship",
    category: "popular",
    status: "delivered",
  },
  {
    id: "JOB4",
    title: "Mobile App Developer",
    description:
      "Desenvolva aplicativos móveis inovadores para diversas plataformas.",
    salary: {
      entry: "85,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "Seattle, WA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Empresa de tecnologia global.",
      reviews: "4.9/5 estrelas",
    },
    type: "Part Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "JOB5",
    title: "Marketing Specialist",
    description:
      "Desenvolva e execute estratégias de marketing para aumentar a visibilidade da marca e atrair clientes.",
    salary: {
      entry: "65,000",
      end: "85,000",
      symbol: "$",
      time: "ano",
    },
    location: "Austin, TX",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/instagram.png",
      name: "Instagram",
      about: "Plataforma de compartilhamento de fotos e vídeos.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB6",
    title: "Cybersecurity Analyst",
    description:
      "Implemente medidas de segurança para proteger os sistemas e dados da empresa contra ameaças cibernéticas.",
    salary: {
      entry: "90,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Washington, D.C.",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/facebook.png",
      name: "Facebook",
      about: "Rede social global.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "analyzing",
  },
  {
    id: "JOB8",
    title: "Cloud Solutions Architect",
    description:
      "Projete e implemente arquiteturas de nuvem eficientes para otimizar a infraestrutura da empresa.",
    salary: {
      entry: "100,000",
      end: "130,000",
      symbol: "$",
      time: "ano",
    },
    location: "London, UK",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Plataforma de armazenamento em nuvem.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "delivered",
  },
  {
    id: "JOB9",
    title: "Graphic Designer",
    description:
      "Crie designs visuais atraentes e inovadores para comunicações de marca e materiais promocionais.",
    salary: {
      entry: "70,000",
      end: "90,000",
      symbol: "$",
      time: "ano",
    },
    location: "Paris, France",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/behance.png",
      name: "Behance",
      about: "Plataforma de portfólios criativos.",
      reviews: "4.6/5 estrelas",
    },
    type: "Part Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "JOB10",
    title: "AI Research Scientist",
    description:
      "Conduza pesquisas inovadoras em inteligência artificial para impulsionar avanços tecnológicos.",
    salary: {
      entry: "110,000",
      end: "140,000",
      symbol: "$",
      time: "ano",
    },
    location: "Berlin, Germany",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Empresa de tecnologia global.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB11",
    title: "Product Manager",
    description:
      "Liderar o ciclo de vida do produto, desde o conceito até o lançamento, garantindo o sucesso no mercado.",
    salary: {
      entry: "95,000",
      end: "125,000",
      symbol: "$",
      time: "ano",
    },
    location: "Austin, TX",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/whatsapp.png",
      name: "WhatsApp",
      about: "Aplicativo de mensagens instantâneas.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "delivered",
  },
  {
    id: "JOB12",
    title: "DevOps Engineer",
    description:
      "Automatize processos de desenvolvimento e operações para melhorar a eficiência e a entrega contínua.",
    salary: {
      entry: "85,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "Seattle, WA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/github.png",
      name: "GitHub",
      about: "Plataforma de desenvolvimento colaborativo.",
      reviews: "4.9/5 estrelas",
    },
    type: "Internship",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB13",
    title: "Content Writer",
    description:
      "Crie conteúdo persuasivo e envolvente para blogs, redes sociais e outros canais de comunicação.",
    salary: {
      entry: "60,000",
      end: "80,000",
      symbol: "$",
      time: "ano",
    },
    location: "London, UK",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/pinterest.png",
      name: "Pinterest",
      about: "Plataforma de descoberta visual.",
      reviews: "4.7/5 estrelas",
    },
    type: "Part Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB14",
    title: "Front-end Developer",
    description:
      "Crie interfaces de usuário interativas e responsivas usando as mais recentes tecnologias web.",
    salary: {
      entry: "75,000",
      end: "100,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/spotify.png",
      name: "Spotify",
      about: "Plataforma de streaming de música.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "JOB15",
    title: "Financial Analyst",
    description:
      "Analise dados financeiros, prepare relatórios e forneça insights para apoiar a tomada de decisões estratégicas.",
    salary: {
      entry: "70,000",
      end: "90,000",
      symbol: "$",
      time: "ano",
    },
    location: "New York, NY",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/paypal.png",
      name: "PayPal",
      about: "Plataforma de pagamento online.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB16",
    title: "Digital Marketing Specialist",
    description:
      "Crie e execute campanhas de marketing digital para aumentar a presença online da empresa.",
    salary: {
      entry: "80,000",
      end: "105,000",
      symbol: "$",
      time: "ano",
    },
    location: "Berlin, Germany",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/instagram.png",
      name: "Instagram",
      about: "Plataforma de compartilhamento de fotos e vídeos.",
      reviews: "4.7/5 estrelas",
    },
    type: "Part Time",
    category: "popular",
    status: "delivered",
  },
  {
    id: "JOB17",
    title: "Network Engineer",
    description:
      "Projetar e gerenciar redes de computadores para garantir conectividade eficiente e segura.",
    salary: {
      entry: "90,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "Tokyo, Japan",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/twitch.png",
      name: "Twitch",
      about: "Plataforma de streaming ao vivo.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "JOB18",
    title: "Human Resources Manager",
    description:
      "Gerencie atividades relacionadas a recursos humanos, recrutamento e desenvolvimento de pessoal.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Paris, France",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/linkedin.png",
      name: "LinkedIn",
      about: "Rede profissional online.",
      reviews: "4.8/5 estrelas",
    },
    type: "Internship",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB19",
    title: "Healthcare Data Analyst",
    description:
      "Analisar dados de saúde para identificar tendências, padrões e insights valiosos para melhorar o atendimento.",
    salary: {
      entry: "85,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "Los Angeles, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/behance.png",
      name: "Behance",
      about: "Plataforma de portfólios criativos.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "delivered",
  },
  {
    id: "JOB20",
    title: "AI Ethics Researcher",
    description:
      "Pesquise e desenvolva diretrizes éticas para o uso responsável de inteligência artificial.",
    salary: {
      entry: "100,000",
      end: "130,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Empresa de tecnologia global.",
      reviews: "4.9/5 estrelas",
    },
    type: "Part Time",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB21",
    title: "Robotics Engineer",
    description:
      "Projete e desenvolva sistemas robóticos avançados para automação industrial e tarefas especializadas.",
    salary: {
      entry: "110,000",
      end: "140,000",
      symbol: "$",
      time: "ano",
    },
    location: "Berlin, Germany",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/discord.png",
      name: "Discord",
      about: "Plataforma de comunicação para gamers.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB22",
    title: "E-commerce Specialist",
    description:
      "Gerencie estratégias de comércio eletrônico, desde a aquisição de clientes até a otimização da experiência de compra.",
    salary: {
      entry: "85,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "New York, NY",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/whatsapp.png",
      name: "WhatsApp",
      about: "Aplicativo de mensagens instantâneas.",
      reviews: "4.8/5 estrelas",
    },
    type: "Internship",
    category: "recent-posted",
    status: "delivered",
  },
  {
    id: "JOB23",
    title: "Environmental Scientist",
    description:
      "Conduza pesquisas ambientais e avaliações para desenvolver soluções sustentáveis para questões ambientais.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Paris, France",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/instagram.png",
      name: "Instagram",
      about: "Plataforma de compartilhamento de fotos e vídeos.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB24",
    title: "Legal Counsel",
    description:
      "Fornecer aconselhamento jurídico em questões corporativas, contratuais e regulatórias.",
    salary: {
      entry: "100,000",
      end: "130,000",
      symbol: "$",
      time: "ano",
    },
    location: "Tokyo, Japan",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/linkedin.png",
      name: "LinkedIn",
      about: "Rede profissional online.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "analyzing",
  },
  {
    id: "JOB25",
    title: "Artificial Intelligence Trainer",
    description:
      "Treine modelos de IA, ajuste algoritmos e melhore o desempenho de sistemas de aprendizado de máquina.",
    salary: {
      entry: "80,000",
      end: "105,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Plataforma de armazenamento em nuvem.",
      reviews: "4.8/5 estrelas",
    },
    type: "Part Time",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB27",
    title: "Supply Chain Analyst",
    description:
      "Otimize processos logísticos e gerencie eficientemente a cadeia de suprimentos da empresa.",
    salary: {
      entry: "75,000",
      end: "100,000",
      symbol: "$",
      time: "ano",
    },
    location: "London, UK",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/twitch.png",
      name: "Twitch",
      about: "Plataforma de streaming ao vivo.",
      reviews: "4.6/5 estrelas",
    },
    type: "Internship",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "JOB28",
    title: "Biomedical Researcher",
    description:
      "Realize pesquisas biomédicas para avançar na compreensão e tratamento de doenças.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Seattle, WA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/spotify.png",
      name: "Spotify",
      about: "Plataforma de streaming de música.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB29",
    title: "Quantum Computing Researcher",
    description:
      "Conduza pesquisas avançadas em computação quântica para impulsionar inovações tecnológicas.",
    salary: {
      entry: "110,000",
      end: "140,000",
      symbol: "$",
      time: "ano",
    },
    location: "Austin, TX",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/github.png",
      name: "GitHub",
      about: "Plataforma de desenvolvimento colaborativo.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "delivered",
  },
  {
    id: "JOB30",
    title: "Renewable Energy Engineer",
    description:
      "Desenvolva soluções de energia renovável para promover a sustentabilidade ambiental.",
    salary: {
      entry: "100,000",
      end: "130,000",
      symbol: "$",
      time: "ano",
    },
    location: "Tokyo, Japan",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Plataforma de armazenamento em nuvem.",
      reviews: "4.8/5 estrelas",
    },
    type: "Internship",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB31",
    title: "Blockchain Developer",
    description:
      "Desenvolva soluções blockchain seguras e eficientes para aplicativos descentralizados.",
    salary: {
      entry: "90,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "Berlin, Germany",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/instagram.png",
      name: "Instagram",
      about: "Plataforma de compartilhamento de fotos e vídeos.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "analyzing",
  },
  {
    id: "JOB32",
    title: "3D Game Artist",
    description:
      "Crie ativos visuais 3D incríveis para jogos, garantindo uma experiência imersiva para os jogadores.",
    salary: {
      entry: "80,000",
      end: "105,000",
      symbol: "$",
      time: "ano",
    },
    location: "Paris, France",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/whatsapp.png",
      name: "WhatsApp",
      about: "Aplicativo de mensagens instantâneas.",
      reviews: "4.8/5 estrelas",
    },
    type: "Part Time",
    category: "popular",
    status: "delivered",
  },
  {
    id: "JOB33",
    title: "Augmented Reality Developer",
    description:
      "Crie experiências de realidade aumentada inovadoras para aplicativos móveis e plataformas AR.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "New York, NY",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/linkedin.png",
      name: "LinkedIn",
      about: "Rede profissional online.",
      reviews: "4.8/5 estrelas",
    },
    type: "Internship",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "JOB34",
    title: "Quantitative Analyst",
    description:
      "Analise dados financeiros e estatísticos para tomar decisões informadas em investimentos.",
    salary: {
      entry: "100,000",
      end: "130,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/behance.png",
      name: "Behance",
      about: "Plataforma de portfólios criativos.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB35",
    title: "Mobile App Product Manager",
    description:
      "Liderar o desenvolvimento e lançamento de aplicativos móveis, garantindo a entrega de produtos de alta qualidade.",
    salary: {
      entry: "110,000",
      end: "140,000",
      symbol: "$",
      time: "ano",
    },
    location: "Tokyo, Japan",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/spotify.png",
      name: "Spotify",
      about: "Plataforma de streaming de música.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "delivered",
  },
  {
    id: "JOB36",
    title: "Social Media Manager",
    description:
      "Gerencie estratégias de mídia social, crie conteúdo e interaja com a comunidade online da empresa.",
    salary: {
      entry: "75,000",
      end: "100,000",
      symbol: "$",
      time: "ano",
    },
    location: "London, UK",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Plataforma de armazenamento em nuvem.",
      reviews: "4.8/5 estrelas",
    },
    type: "Part Time",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB37",
    title: "HealthTech Software Engineer",
    description:
      "Desenvolva software para soluções de tecnologia da saúde, focando em inovações para melhorar o setor.",
    salary: {
      entry: "85,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "Los Angeles, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/github.png",
      name: "GitHub",
      about: "Plataforma de desenvolvimento colaborativo.",
      reviews: "4.9/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "analyzing",
  },
  {
    id: "JOB39",
    title: "Machine Translation Specialist",
    description:
      "Desenvolva e aprimore algoritmos de tradução automática para melhorar a comunicação global.",
    salary: {
      entry: "100,000",
      end: "130,000",
      symbol: "$",
      time: "ano",
    },
    location: "Seattle, WA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/spotify.png",
      name: "Spotify",
      about: "Plataforma de streaming de música.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB40",
    title: "Space Exploration Scientist",
    description:
      "Conduza pesquisas avançadas para impulsionar a exploração espacial e o desenvolvimento de tecnologias espaciais.",
    salary: {
      entry: "110,000",
      end: "140,000",
      symbol: "$",
      time: "ano",
    },
    location: "Paris, France",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Empresa de tecnologia global.",
      reviews: "4.9/5 estrelas",
    },
    type: "Part Time",
    category: "recent-posted",
    status: "analyzing",
  },
  {
    id: "JOB41",
    title: "Cybersecurity Analyst",
    description:
      "Analise e proteja sistemas contra ameaças cibernéticas, implementando medidas de segurança avançadas.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Berlin, Germany",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/dropbox.png",
      name: "Dropbox",
      about: "Plataforma de armazenamento em nuvem.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "recent-posted",
    status: "analyzing",
  },
  {
    id: "JOB42",
    title: "Renewable Energy Researcher",
    description:
      "Conduza pesquisas para avançar em tecnologias de energia renovável e promover a sustentabilidade.",
    salary: {
      entry: "100,000",
      end: "130,000",
      symbol: "$",
      time: "ano",
    },
    location: "Paris, France",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/github.png",
      name: "GitHub",
      about: "Plataforma de desenvolvimento colaborativo.",
      reviews: "4.9/5 estrelas",
    },
    type: "Internship",
    category: "popular",
    status: "delivered",
  },
  {
    id: "JOB43",
    title: "Data Privacy Officer",
    description:
      "Garanta a conformidade com regulamentos de privacidade de dados e implemente práticas seguras de gestão de dados.",
    salary: {
      entry: "85,000",
      end: "110,000",
      symbol: "$",
      time: "ano",
    },
    location: "New York, NY",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/twitch.png",
      name: "Twitch",
      about: "Plataforma de streaming ao vivo.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB44",
    title: "UX/UI Designer",
    description:
      "Crie experiências de usuário intuitivas e visualmente atraentes para aplicativos e sites.",
    salary: {
      entry: "110,000",
      end: "140,000",
      symbol: "$",
      time: "ano",
    },
    location: "San Francisco, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/instagram.png",
      name: "Instagram",
      about: "Plataforma de compartilhamento de fotos e vídeos.",
      reviews: "4.7/5 estrelas",
    },
    type: "Part Time",
    category: "recent-posted",
    status: "delivered",
  },

  {
    id: "JOB45",
    title: "Autonomous Vehicle Engineer",
    description:
      "Desenvolva sistemas avançados para veículos autônomos, garantindo segurança e eficiência.",
    salary: {
      entry: "80,000",
      end: "105,000",
      symbol: "$",
      time: "ano",
    },
    location: "London, UK",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/whatsapp.png",
      name: "WhatsApp",
      about: "Aplicativo de mensagens instantâneas.",
      reviews: "4.8/5 estrelas",
    },
    type: "Internship",
    category: "recent-posted",
    status: "pending",
  },
  {
    id: "JOB46",
    title: "Medical Research Scientist",
    description:
      "Conduza estudos médicos para avançar em pesquisas relacionadas a tratamentos e prevenção de doenças.",
    salary: {
      entry: "95,000",
      end: "120,000",
      symbol: "$",
      time: "ano",
    },
    location: "Tokyo, Japan",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/pinterest.png",
      name: "Pinterest",
      about: "Plataforma de descoberta visual.",
      reviews: "4.7/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB47",
    title: "Virtual Reality Artist",
    description:
      "Crie mundos virtuais e experiências imersivas para plataformas de realidade virtual.",
    salary: {
      entry: "75,000",
      end: "100,000",
      symbol: "$",
      time: "ano",
    },
    location: "Los Angeles, CA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/paypal.png",
      name: "PayPal",
      about: "Plataforma de pagamento online.",
      reviews: "4.8/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "analyzing",
  },
  {
    id: "JOB48",
    title: "Climate Change Analyst",
    description:
      "Analise dados e tendências climáticas para informar políticas e estratégias de combate às mudanças climáticas.",
    salary: {
      entry: "90,000",
      end: "115,000",
      symbol: "$",
      time: "ano",
    },
    location: "Austin, TX",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/linkedin.png",
      name: "LinkedIn",
      about: "Rede profissional online.",
      reviews: "4.8/5 estrelas",
    },
    type: "Part Time",
    category: "recent-posted",
    status: "delivered",
  },
  {
    id: "JOB49",
    title: "AR/VR Game Developer",
    description:
      "Desenvolva jogos envolventes e inovadores para plataformas de realidade aumentada e virtual.",
    salary: {
      entry: "100,000",
      end: "130,000",
      symbol: "$",
      time: "ano",
    },
    location: "Seattle, WA",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/twitch.png",
      name: "Twitch",
      about: "Plataforma de streaming ao vivo.",
      reviews: "4.6/5 estrelas",
    },
    type: "Full Time",
    category: "popular",
    status: "pending",
  },
  {
    id: "JOB50",
    title: "Digital Marketing Specialist",
    description:
      "Crie e execute estratégias de marketing digital para promover a marca e aumentar a visibilidade online.",
    salary: {
      entry: "110,000",
      end: "140,000",
      symbol: "$",
      time: "ano",
    },
    location: "Berlin, Germany",
    company: {
      logoUrl: "https://api-jobs-finder2.vercel.app/imagens/google.png",
      name: "Google",
      about: "Empresa de tecnologia global.",
      reviews: "4.9/5 estrelas",
    },
    type: "Part Time",
    category: "recent-posted",
    status: "analyzing",
  },
];

export default allJobs;
